import './globals.css'
import localFont from 'next/font/local'

const pixelText = localFont({ src: '../assets/fonts/pixelText.ttf' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pixelText.className}>
        {children}
      </body>
    </html>
  )
}
